AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloudformation Template for kittens carousel static website deploy on s3 through cloudfront and route 53
Parameters:
  myDomainName:
    Description: Type your full domain name 
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    
Resources:
  myS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref myDomainName
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
      WebsiteConfiguration:
        IndexDocument: index.html
  
  myBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref myS3Bucket # Required
      PolicyDocument: # Required
        Version: 2012-10-17
        Statement:
        - Action:
            - 's3:GetObject'
          Effect: Allow
          Resource: !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref myS3Bucket
              - /*
          Principal: '*'
  
  myCloudFrontDist:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref myDomainName
        Comment: ny cloudfront distribution
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 #cloudfront policy bölümünden CachingOptimized'ın numarasını aldık.tavsiye edilen policy bu
          Compress: true
          TargetOriginId: aydin-cfn-aws-19
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: http-only
            DomainName: !Select [2, !Split ["/", !GetAtt myS3Bucket.WebsiteURL]]
            Id: aydin-cfn-aws-19
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:600627361541:certificate/0c6d032e-b610-46ea-a9e6-ec0d0f39dccc
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only

  myRoute53Record:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: Z08419722MNEBZ7I5TT2X
      RecordSets: 
        - AliasTarget:
            DNSName: !GetAtt myCloudFrontDist.DomainName
            HostedZoneId: Z2FDTNDATAQYW2
          Name: !Ref myDomainName
          Type: A
          
Outputs:
  BucketName: 
    Description: Endpoint for S3 Bucket
    Value: !GetAtt myS3Bucket.WebsiteURL
  CloudfrontEndpoint:
    Description: Endpoint for Cloudfront
    Value: !GetAtt myCloudFrontDist.DomainName
  FullDomainName:
    Description: Full Domain Name of Application
    Value: !Ref myDomainName